-- 补充演示优惠券数据：满减券、9折券、8折券、运费券、分类券、指定商品券
-- 说明：当前 coupons 已支持正式 scope / scope_category_ids / scope_product_ids 字段。
-- fixed 表示满减/立减券，percent 表示折扣券，discount_value 存储折扣值（9 =9折，8 =8折）。

insert into public.coupons (
  title,
  description,
  code,
 scope,
  scope_category_ids,
  scope_product_ids,
  discount_type,
  discount_value,
  min_spend,
  max_discount,
  total_limit,
  per_user_limit,
  claimed_count,
  used_count,
 starts_at,
  ends_at,
  is_active
)
values
  (
    '满99减10',
    '单笔订单满99元可用，适合日常购茶。',
    'TEA99MINUS10',
    'all',
    '{}',
    '{}',
    'fixed',
    10,
    99,
    null,
    null,
    1,
    0,
    0,
    timezone('utc', now()),
    timezone('utc', now()) + interval '180 days',
    true
  ),
  (
    '全场9折',
    '单笔订单满128元可用，最高优惠30元。',
    'TEA90OFF',
    'all',
    '{}',
    '{}',
    'percent',
    9,
    128,
    30,
    null,
    1,
    0,
    0,
    timezone('utc', now()),
    timezone('utc', now()) + interval '180 days',
    true
  ),
  (
    '精选8折',
    '单笔订单满188元可用，最高优惠60元。',
    'TEA80OFF',
    'all',
    '{}',
    '{}',
    'percent',
    8,
188,
    60,
    null,
    1,
    0,
    0,
    timezone('utc', now()),
    timezone('utc', now()) + interval '180 days',
    true
 ),
  (
    '运费立减券',
    '下单可抵扣运费，最高抵扣12元。',
    'SHIP12',
    'shipping',
    '{}',
    '{}',
    'fixed',
    12,
    0,
    12,
    null,
    1,
0,
    0,
    timezone('utc', now()),
    timezone('utc', now()) + interval '180 days',
    true
  ),
  (
    '绿茶品类满199减25',
    '仅限绿茶分类商品使用，满199元减25元。',
    'GREEN199MINUS25',
    'category',
    '{绿茶}',
    '{}',
    'fixed',
    25,
    199,
    null,
    null,
    1,
 0,
    0,
    timezone('utc', now()),
    timezone('utc', now()) + interval '180 days',
    true
  ),
  (
    '指定商品9折券',
    '仅限指定商品使用，满99元可用，最高优惠20元。',
    'SKU90OFF',
    'product',
    '{}',
    '{}',
    'percent',
    9,
    99,
    20,
    null,
    1,
    0,
    0,
    timezone('utc', now()),
    timezone('utc', now()) + interval '180 days',
    true
  )
on conflict (code) do update
set
  title = excluded.title,
 description = excluded.description,
 scope = excluded.scope,
 scope_category_ids = excluded.scope_category_ids,
 scope_product_ids = excluded.scope_product_ids,
 discount_type = excluded.discount_type,
  discount_value = excluded.discount_value,
  min_spend = excluded.min_spend,
  max_discount = excluded.max_discount,
  total_limit = excluded.total_limit,
  per_user_limit = excluded.per_user_limit,
  is_active = excluded.is_active,
  starts_at = excluded.starts_at,
  ends_at = excluded.ends_at,
  updated_at = timezone('utc', now());
